### ISSUE TITLE
WinHTTP user agent

### ISSUE THREAD

**Issue by Alisa-lisa** [rguerreiro/device#12]
it is highly probable that a request with user agent "WinHTTP" comes from a scraper. In som e resources it is even said to be a part of the virus. Could you add it to the bot list please?

Some more info: 
1. https://user-agents.me/useragent/mozilla40-compatible-win32-winhttpwinhttprequest5
2. https://msdn.microsoft.com/en-us/library/aa382925(VS.85).aspx

**Comment by rguerreiro** [comment]
Maybe should add a flag **suspect**. What do you think?
