### ISSUE TITLE
Go-http-client wrong device detect

### ISSUE THREAD

**Issue by idexter** [rguerreiro/device#16]
When I try to request my api with golang (By default, user agent is: "Go-http-client/1.1")
I have device type "phone", because my User-Agent is Unknown. But this is not a phone. I think this behaviour, when you set `unknownUserAgentDeviceType: 'phone'`, is strange and wrong.
Can you add "Go-http-client" to desktop section?

**Comment by rguerreiro** [comment]
Not sure if should be desktop or bot. What do you think?

Sorry for the delay ;)

**Comment by idexter** [comment]
I think bot it is not device actually. :) Device detection in UserAgent in often uses for UI purposes and in this case many libraries in over stacks (node.js for example) set device as desktop by default. IMHO desktop is the most common device and it should be used by default.

**Comment by rguerreiro** [comment]
I do agree that desktop is most often the default type, although phone is catching up quicky. But this package is being used for many other use cases than just for UI purposes. In that matter bot is an acceptable device type.

**Comment by idexter** [comment]
Yes. I think you are right. Even if it will be used for UI purpose, `bot` is more prefer by default. It sounds like `Sorry I can't detect is it mobile or desktop? So it is probably something else.`.

**Comment by rguerreiro** [comment]
it's fixed. it returns 'desktop'
