### ISSUE TITLE
getting empty response for get_model()!

### ISSUE THREAD

**Issue by nikunjdnp** [rguerreiro/device#20]
Hi,
I am getting undefined for get_model().

Ex: 
`{ parser: 
   DeviceParser {
     options: 
      { emptyUserAgentDeviceType: 'desktop',
        unknownUserAgentDeviceType: 'phone',
        botUserAgentDeviceType: 'bot',
        carUserAgentDeviceType: 'car',
        parseUserAgent: false },
     make_sure_parser_was_executed: [Function],
     get_model: [Function],
     get_type: [Function] },
  type: 'phone',
  model: '',
  is: [Function: is] }`

and my api response is : " "
empty for getmodel().

UserAgent is  Mozilla/5.0 (Linux; Android 7.0; Redmi Note 4 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

**Comment by rguerreiro** [comment]
Please you need to elaborate more. Post the code your using to setup device
