### ISSUE TITLE
Bug Fix Reporting and QA Guides?

### ISSUE THREAD

**Issue by Econac** [rguerreiro/device#23]
Hi, what is the correct way to report a bug or trigger some QA procedure here? In my instance, the module fails to recognise latest Chrome, Firefox and Edge on Windows 10 Pro 64. What test you like me to run and what report you want me to submit in order to clear this up? Please note that I am aware that it might be my very local issue, hence I am not really pushing it ahead as a confirmed bug. I would rather first run some tests before submitting the bug report, thought I am not sure what the bug fixing policy is optimal for you.

**Comment by rguerreiro** [comment]
You can submit a pull request (including a test on the specific file on the **test** folder) or just include the failing user agent string here
