### ISSUE TITLE
Error: Cannot find module "../package"

### ISSUE THREAD

**Issue by maxletourneur** [rguerreiro/device#24]
Great work!

Using webpack 2, I'm running into this error where the relative reference to package module in ./node_modules/device/lib/device.js breaks.

Seems normal as it looks for "package" in ./node_modules/device folder while it should be looking for it in ./node_modules.

**Comment by maxletourneur** [comment]
Fixed it by adding .json in webpack config resolve rule:
resolve: {
  extensions: ['.ts', '.tsx', '.js', '.jsx', '.json']
},

**Comment by luchillo17** [comment]
I can't change the extensions, didn't got permission to eject the app, can't we just change the require from `package` to `package.json`?
