### ISSUE TITLE
No iPhone rule

### ISSUE THREAD

**Issue by neeh** [rguerreiro/device#31]
Here's an iPhone 10 user agent string which is not recognized as `"phone"` by the library (falling back to the unknown device).

`Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Snapchat/10.47.5.13 (iPhone10,1; iOS 12.1.2; gzip)`

Seems like an `iPhone` options is missing in the regex on this line: https://github.com/rguerreiro/device/blob/2a8bd17337a9853fb1cd8f019e0c803e3c2a330e/lib/device.js#L80-L82

**Comment by rguerreiro** [comment]
I've added a test specifically for the user-agent you mention and the test run with success.

You can see it here: https://github.com/rguerreiro/device/blob/816306e7a4a23cefde305d95a8bac30d97b77253/test/device_phone_6_test.js#L1781
